<?php

namespace App\Services;

use App\Models\TechnicalAnalysis;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TechnicalAnalysisGeneratorService
{
    public function __construct(
        protected TechnicalContextService $technicalContextService,
        protected TechnicalAnalysisPromptService $promptService,
    ) {}

    public function generate(string $symbol, string $executionTimeframe): ?TechnicalAnalysis
    {
        $symbol = strtoupper($symbol);
        $executionTimeframe = strtoupper($executionTimeframe);

        $latestCandleTime = DB::table('market_data')
            ->where('symbol', $symbol)
            ->where('timeframe', $executionTimeframe)
            ->max('tick_time');

        if (! $latestCandleTime) {
            return null;
        }

        $alreadyExists = TechnicalAnalysis::query()
            ->where('symbol', $symbol)
            ->where('execution_timeframe', $executionTimeframe)
            ->where('context_candle_time', $latestCandleTime)
            ->exists();

        if ($alreadyExists) {
            return null;
        }

        $context = $this->buildContext($symbol, $executionTimeframe);

        $context['symbol'] = $context['symbol'] ?? $symbol;
        $context['execution_timeframe'] = $context['execution_timeframe'] ?? $executionTimeframe;
        $context['context_candle_time'] = $latestCandleTime;

        $promptText = $this->promptService->build($context);

        return TechnicalAnalysis::create([
            'analysis_uuid' => (string) Str::uuid(),
            'symbol' => $symbol,
            'execution_timeframe' => $executionTimeframe,
            'higher_timeframe_bias' => $this->contextValue($context, [
                'higher_timeframe_bias',
                'bias.higher_timeframe_bias',
                'summary.higher_timeframe_bias',
            ], 'neutral'),
            'execution_bias' => $this->contextValue($context, [
                'execution_bias',
                'bias.execution_bias',
                'summary.execution_bias',
            ], 'neutral'),
            'preferred_action' => $this->contextValue($context, [
                'preferred_action',
                'summary.preferred_action',
            ], 'WAIT'),
            'current_price' => $this->contextValue($context, [
                'current_price',
                'price.current',
                'latest.close',
                'summary.current_price',
            ]),
            'context_candle_time' => $latestCandleTime,
            'raw_context_json' => $context,
            'prompt_text' => $promptText,
            'agent_name' => 'OpenClaw Technical Agent',
            'agent_model' => null,
            'decision' => null,
            'confidence' => null,
            'reason_summary' => null,
            'reasons_json' => null,
            'status' => 'GENERATED',
            'notes' => 'Auto generated by Laravel Scheduler.',
        ]);
    }

    private function buildContext(string $symbol, string $executionTimeframe): array
    {
        foreach (['build', 'generate', 'getContext', 'analyze'] as $method) {
            if (method_exists($this->technicalContextService, $method)) {
                $result = $this->technicalContextService->{$method}($symbol, $executionTimeframe);

                if (is_array($result)) {
                    return $result;
                }

                if (is_object($result) && method_exists($result, 'toArray')) {
                    return $result->toArray();
                }
            }
        }

        throw new \RuntimeException(
            'TechnicalContextService tidak punya method build/generate/getContext/analyze. Sesuaikan nama method di TechnicalAnalysisGeneratorService.'
        );
    }

    private function contextValue(array $context, array $paths, mixed $default = null): mixed
    {
        foreach ($paths as $path) {
            $value = data_get($context, $path);

            if ($value !== null) {
                return $value;
            }
        }

        return $default;
    }
}