<?php

namespace App\Http\Controllers;

use App\Models\TechnicalAnalysis;
use App\Models\TradingBotPair;
use App\Services\TechnicalAnalysisPromptService;
use App\Services\TechnicalContextService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TechnicalAnalysisWorkflowController extends Controller
{
    public function index(Request $request)
    {
        $analyses = TechnicalAnalysis::query()
            ->with('tradeSignals')
            ->when($request->filled('symbol'), function ($query) use ($request) {
                $query->where('symbol', $request->symbol);
            })
            ->when($request->filled('execution_timeframe'), function ($query) use ($request) {
                $query->where('execution_timeframe', $request->execution_timeframe);
            })
            ->when($request->filled('status'), function ($query) use ($request) {
                $query->where('status', $request->status);
            })
            ->latest('created_at')
            ->get();

        $symbols = TechnicalAnalysis::query()
            ->select('symbol')
            ->distinct()
            ->orderBy('symbol')
            ->pluck('symbol');

        $timeframes = TechnicalAnalysis::query()
            ->select('execution_timeframe')
            ->distinct()
            ->orderBy('execution_timeframe')
            ->pluck('execution_timeframe');

        $summary = TechnicalAnalysis::query()
            ->select('status', DB::raw('COUNT(*) as total'))
            ->groupBy('status')
            ->pluck('total', 'status');

        return view('technical.analyses.index', compact(
            'analyses',
            'symbols',
            'timeframes',
            'summary'
        ));
    }

    public function generate(
        Request $request,
        TechnicalContextService $technicalContextService,
        TechnicalAnalysisPromptService $promptService
    ) {
        $validated = $request->validate([
            'symbol' => ['required', 'string', 'max:20'],
            'execution_timeframe' => ['required', 'string', 'max:10'],
        ]);

        $symbol = strtoupper($validated['symbol']);
        $executionTimeframe = strtoupper($validated['execution_timeframe']);

        $context = $this->buildContext(
            $technicalContextService,
            $symbol,
            $executionTimeframe
        );

        $context['symbol'] = $context['symbol'] ?? $symbol;
        $context['execution_timeframe'] = $context['execution_timeframe'] ?? $executionTimeframe;
        $context['agent_profile'] = $this->resolveAgentProfile($symbol, $executionTimeframe);

        $promptText = $promptService->build($context);

        $analysis = TechnicalAnalysis::create([
            'analysis_uuid' => (string) Str::uuid(),
            'symbol' => $symbol,
            'execution_timeframe' => $executionTimeframe,
            'higher_timeframe_bias' => $this->contextValue($context, [
                'smc_summary.higher_timeframe_bias',
                'higher_timeframe_bias',
                'bias.higher_timeframe_bias',
                'summary.higher_timeframe_bias',
            ], 'neutral'),
            'execution_bias' => $this->contextValue($context, [
                'smc_summary.execution_bias',
                'execution_bias',
                'bias.execution_bias',
                'summary.execution_bias',
            ], 'neutral'),
            'preferred_action' => $this->contextValue($context, [
                'smc_summary.preferred_action',
                'preferred_action',
                'summary.preferred_action',
            ], 'WAIT'),
            'current_price' => $this->contextValue($context, [
                'current_price',
                'price.current',
                'latest.close',
                'summary.current_price',
            ]),
            'raw_context_json' => $context,
            'prompt_text' => $promptText,
            'agent_name' => 'OpenClaw Technical Agent',
            'agent_model' => null,
            'decision' => null,
            'confidence' => null,
            'reason_summary' => null,
            'reasons_json' => null,
            'status' => 'GENERATED',
            'notes' => 'Generated by Laravel Control Tower.',
        ]);

        if ($request->expectsJson()) {
            return response()->json([
                'success' => true,
                'message' => 'Technical analysis generated.',
                'data' => $analysis,
            ]);
        }

        return redirect()
            ->route('technical-analyses.index')
            ->with('success', 'Technical analysis berhasil di-generate.');
    }

    public function show(TechnicalAnalysis $technicalAnalysis)
    {
        $technicalAnalysis->load('tradeSignals');

        return view('technical.analyses.show', compact('technicalAnalysis'));
    }

    public function pendingTechnicalAnalyses(Request $request)
    {
        $validated = $request->validate([
            'symbol' => ['nullable', 'string', 'max:20'],
            'execution_timeframe' => ['nullable', 'string', 'max:10'],
            'limit' => ['nullable', 'integer', 'min:1', 'max:50'],
            'mark_sent' => ['nullable', 'boolean'],
        ]);

        $limit = (int) ($validated['limit'] ?? 10);
        $markSent = $request->boolean('mark_sent', true);

        return DB::transaction(function () use ($validated, $limit, $markSent) {
            $analyses = TechnicalAnalysis::query()
                ->where('status', 'GENERATED')
                ->when(isset($validated['symbol']), function ($query) use ($validated) {
                    $query->where('symbol', strtoupper($validated['symbol']));
                })
                ->when(isset($validated['execution_timeframe']), function ($query) use ($validated) {
                    $query->where('execution_timeframe', strtoupper($validated['execution_timeframe']));
                })
                ->orderBy('created_at')
                ->limit($limit)
                ->lockForUpdate()
                ->get();

            if ($markSent && $analyses->isNotEmpty()) {
                $analyses->each(function (TechnicalAnalysis $analysis) {
                    $analysis->update([
                        'status' => 'SENT_TO_TECHNICAL_AGENT',
                        'notes' => $this->appendNote($analysis->notes, 'Sent to Technical Agent.'),
                    ]);
                });

                $analyses = TechnicalAnalysis::query()
                    ->whereIn('id', $analyses->pluck('id'))
                    ->orderBy('created_at')
                    ->get();
            }

            return response()->json([
                'success' => true,
                'message' => $analyses->isEmpty()
                    ? 'No pending technical analyses.'
                    : 'Pending technical analyses retrieved.',
                'data' => $analyses->map(fn (TechnicalAnalysis $analysis) => [
                    'id' => $analysis->id,
                    'analysis_uuid' => $analysis->analysis_uuid,
                    'symbol' => $analysis->symbol,
                    'execution_timeframe' => $analysis->execution_timeframe,
                    'context_candle_time' => optional($analysis->context_candle_time)->toDateTimeString(),
                    'higher_timeframe_bias' => $analysis->higher_timeframe_bias,
                    'execution_bias' => $analysis->execution_bias,
                    'preferred_action' => $analysis->preferred_action,
                    'current_price' => $analysis->current_price,
                    'raw_context_json' => $analysis->raw_context_json,
                    'prompt_text' => $analysis->prompt_text,
                    'status' => $analysis->status,
                ]),
            ]);
        });
    }

    public function technicalResult(Request $request, TechnicalAnalysis $technicalAnalysis)
    {
        $validated = $request->validate([
            'decision' => ['required', 'string', 'in:BUY,SELL,NO_TRADE'],
            'confidence' => ['required', 'integer', 'min:0', 'max:100'],
            'reason_summary' => ['nullable', 'string'],
            'reasons' => ['nullable', 'array'],
            'technical_setup' => ['nullable', 'array'],
            'agent_name' => ['nullable', 'string', 'max:100'],
            'agent_model' => ['nullable', 'string', 'max:100'],

            'signal' => ['nullable', 'array'],
            'signal.entry_type' => ['nullable', 'string', 'max:20'],
            'signal.entry_price' => ['nullable', 'numeric'],
            'signal.stop_loss' => ['nullable', 'numeric'],
            'signal.take_profit_1' => ['nullable', 'numeric'],
            'signal.take_profit_2' => ['nullable', 'numeric'],
            'signal.take_profit_3' => ['nullable', 'numeric'],
            'signal.risk_reward' => ['nullable', 'numeric'],
            'signal.risk_percent' => ['nullable', 'numeric'],
            'signal.lot_size' => ['nullable', 'numeric'],
            'signal.invalidation' => ['nullable', 'string'],
        ]);

        return DB::transaction(function () use ($validated, $request, $technicalAnalysis) {
            $decision = strtoupper($validated['decision']);

            $technicalAnalysis->update([
                'ai_response_json' => $request->all(),
                'agent_name' => $validated['agent_name'] ?? 'OpenClaw Technical Agent',
                'agent_model' => $validated['agent_model'] ?? null,
                'decision' => $decision,
                'confidence' => $validated['confidence'],
                'reason_summary' => $validated['reason_summary'] ?? null,
                'reasons_json' => $validated['reasons'] ?? [],
                'status' => 'TECHNICAL_COMPLETED',
                'notes' => $this->appendNote($technicalAnalysis->notes, 'Technical Agent result received.'),
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Technical result saved. No trade signal created.',
                'technical_analysis' => $technicalAnalysis->fresh(),
            ]);
        });
    }

    public function aiResult(Request $request, TechnicalAnalysis $technicalAnalysis)
    {
        return $this->technicalResult($request, $technicalAnalysis);
    }

    private function buildContext(
        TechnicalContextService $service,
        string $symbol,
        string $executionTimeframe
    ): array {
        foreach (['build', 'generate', 'getContext', 'analyze'] as $method) {
            if (method_exists($service, $method)) {
                $result = $service->{$method}($symbol, $executionTimeframe);

                if (is_array($result)) {
                    return $result;
                }

                if (method_exists($result, 'toArray')) {
                    return $result->toArray();
                }
            }
        }

        throw new \RuntimeException(
            'TechnicalContextService tidak punya method build/generate/getContext/analyze. Sesuaikan nama method di controller.'
        );
    }

    private function contextValue(array $context, array $paths, mixed $default = null): mixed
    {
        foreach ($paths as $path) {
            $value = data_get($context, $path);

            if ($value !== null) {
                return $value;
            }
        }

        return $default;
    }

    private function resolveAgentProfile(string $symbol, string $executionTimeframe): array
    {
        $pair = TradingBotPair::query()
            ->where('symbol', $symbol)
            ->where('entry_timeframe', $executionTimeframe)
            ->first();

        return $pair?->agentProfile() ?? TradingBotPair::defaultAgentProfile();
    }

    private function appendNote(?string $oldNote, ?string $newNote): string
    {
        $newNote = trim((string) $newNote);

        if ($newNote === '') {
            return (string) $oldNote;
        }

        $timestamp = now()->format('Y-m-d H:i:s');

        return trim(($oldNote ? $oldNote . PHP_EOL : '') . '[' . $timestamp . '] ' . $newNote);
    }
}
