<?php

namespace App\Http\Controllers;

use App\Models\TechnicalAnalysis;
use App\Models\TradeSignal;
use App\Services\TechnicalAnalysisPromptService;
use App\Services\TechnicalContextService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TechnicalAnalysisWorkflowController extends Controller
{
    public function index(Request $request)
    {
        $analyses = TechnicalAnalysis::query()
            ->with('tradeSignals')
            ->when($request->filled('symbol'), function ($query) use ($request) {
                $query->where('symbol', $request->symbol);
            })
            ->when($request->filled('execution_timeframe'), function ($query) use ($request) {
                $query->where('execution_timeframe', $request->execution_timeframe);
            })
            ->when($request->filled('status'), function ($query) use ($request) {
                $query->where('status', $request->status);
            })
            ->latest('created_at')
            ->paginate(20)
            ->withQueryString();

        $symbols = TechnicalAnalysis::query()
            ->select('symbol')
            ->distinct()
            ->orderBy('symbol')
            ->pluck('symbol');

        $timeframes = TechnicalAnalysis::query()
            ->select('execution_timeframe')
            ->distinct()
            ->orderBy('execution_timeframe')
            ->pluck('execution_timeframe');

        $summary = TechnicalAnalysis::query()
            ->select('status', DB::raw('COUNT(*) as total'))
            ->groupBy('status')
            ->pluck('total', 'status');

        return view('technical.analyses.index', compact(
            'analyses',
            'symbols',
            'timeframes',
            'summary'
        ));
    }

    public function generate(
        Request $request,
        TechnicalContextService $technicalContextService,
        TechnicalAnalysisPromptService $promptService
    ) {
        $validated = $request->validate([
            'symbol' => ['required', 'string', 'max:20'],
            'execution_timeframe' => ['required', 'string', 'max:10'],
        ]);

        $symbol = strtoupper($validated['symbol']);
        $executionTimeframe = strtoupper($validated['execution_timeframe']);

        $context = $this->buildContext(
            $technicalContextService,
            $symbol,
            $executionTimeframe
        );

        $context['symbol'] = $context['symbol'] ?? $symbol;
        $context['execution_timeframe'] = $context['execution_timeframe'] ?? $executionTimeframe;

        $promptText = $promptService->build($context);

        $analysis = TechnicalAnalysis::create([
            'analysis_uuid' => (string) Str::uuid(),
            'symbol' => $symbol,
            'execution_timeframe' => $executionTimeframe,
            'higher_timeframe_bias' => $this->contextValue($context, [
                'higher_timeframe_bias',
                'bias.higher_timeframe_bias',
                'summary.higher_timeframe_bias',
            ], 'neutral'),
            'execution_bias' => $this->contextValue($context, [
                'execution_bias',
                'bias.execution_bias',
                'summary.execution_bias',
            ], 'neutral'),
            'preferred_action' => $this->contextValue($context, [
                'preferred_action',
                'summary.preferred_action',
            ], 'WAIT'),
            'current_price' => $this->contextValue($context, [
                'current_price',
                'price.current',
                'latest.close',
                'summary.current_price',
            ]),
            'raw_context_json' => $context,
            'prompt_text' => $promptText,
            'agent_name' => 'OpenClaw Technical Agent',
            'agent_model' => null,
            'decision' => null,
            'confidence' => null,
            'reason_summary' => null,
            'reasons_json' => null,
            'status' => 'GENERATED',
            'notes' => 'Generated by Laravel Control Tower.',
        ]);

        if ($request->expectsJson()) {
            return response()->json([
                'success' => true,
                'message' => 'Technical analysis generated.',
                'data' => $analysis,
            ]);
        }

        return redirect()
            ->route('technical-analyses.index')
            ->with('success', 'Technical analysis berhasil di-generate.');
    }

    public function show(TechnicalAnalysis $technicalAnalysis)
    {
        $technicalAnalysis->load('tradeSignals');

        return view('technical.analyses.show', compact('technicalAnalysis'));
    }

    public function aiResult(Request $request, TechnicalAnalysis $technicalAnalysis)
    {
        $validated = $request->validate([
            'decision' => ['required', 'string', 'in:BUY,SELL,NO_TRADE'],
            'confidence' => ['required', 'integer', 'min:0', 'max:100'],
            'reason_summary' => ['nullable', 'string'],
            'reasons' => ['nullable', 'array'],
            'agent_name' => ['nullable', 'string', 'max:100'],
            'agent_model' => ['nullable', 'string', 'max:100'],

            'signal' => ['nullable', 'array'],
            'signal.entry_type' => ['nullable', 'string', 'max:20'],
            'signal.entry_price' => ['nullable', 'numeric'],
            'signal.stop_loss' => ['nullable', 'numeric'],
            'signal.take_profit_1' => ['nullable', 'numeric'],
            'signal.take_profit_2' => ['nullable', 'numeric'],
            'signal.take_profit_3' => ['nullable', 'numeric'],
            'signal.risk_reward' => ['nullable', 'numeric'],
            'signal.risk_percent' => ['nullable', 'numeric'],
            'signal.lot_size' => ['nullable', 'numeric'],
            'signal.invalidation' => ['nullable', 'string'],
        ]);

        return DB::transaction(function () use ($validated, $request, $technicalAnalysis) {
            $decision = strtoupper($validated['decision']);

            $technicalAnalysis->update([
                'ai_response_json' => $request->all(),
                'agent_name' => $validated['agent_name'] ?? 'OpenClaw Technical Agent',
                'agent_model' => $validated['agent_model'] ?? null,
                'decision' => $decision,
                'confidence' => $validated['confidence'],
                'reason_summary' => $validated['reason_summary'] ?? null,
                'reasons_json' => $validated['reasons'] ?? [],
                'status' => 'AI_COMPLETED',
                'notes' => $this->appendNote($technicalAnalysis->notes, 'AI result received.'),
            ]);

            $tradeSignal = null;

            if (in_array($decision, ['BUY', 'SELL'], true)) {
                $signalPayload = $validated['signal'] ?? [];

                $tradeSignal = TradeSignal::firstOrCreate(
                    [
                        'technical_analysis_id' => $technicalAnalysis->id,
                    ],
                    [
                        'signal_uuid' => (string) Str::uuid(),
                        'symbol' => $technicalAnalysis->symbol,
                        'timeframe' => $technicalAnalysis->execution_timeframe,
                        'decision' => $decision,
                        'side' => $decision,
                        'entry_type' => $signalPayload['entry_type'] ?? 'MARKET',
                        'entry_price' => $signalPayload['entry_price'] ?? $technicalAnalysis->current_price,
                        'stop_loss' => $signalPayload['stop_loss'] ?? null,
                        'take_profit_1' => $signalPayload['take_profit_1'] ?? null,
                        'take_profit_2' => $signalPayload['take_profit_2'] ?? null,
                        'take_profit_3' => $signalPayload['take_profit_3'] ?? null,
                        'risk_reward' => $signalPayload['risk_reward'] ?? null,
                        'risk_percent' => $signalPayload['risk_percent'] ?? 1,
                        'lot_size' => $signalPayload['lot_size'] ?? null,
                        'confidence' => $validated['confidence'],
                        'reason_summary' => $validated['reason_summary'] ?? null,
                        'reasons_json' => $validated['reasons'] ?? [],
                        'invalidation' => $signalPayload['invalidation'] ?? null,
                        'status' => 'PENDING',
                        'expired_at' => now()->addMinutes(30),
                        'notes' => 'Created automatically from AI technical analysis.',
                    ]
                );

                $technicalAnalysis->update([
                    'status' => 'SIGNAL_CREATED',
                    'notes' => $this->appendNote($technicalAnalysis->notes, 'Trade signal created.'),
                ]);
            }

            return response()->json([
                'success' => true,
                'message' => $tradeSignal
                    ? 'AI result saved and trade signal created.'
                    : 'AI result saved. No trade signal created.',
                'technical_analysis' => $technicalAnalysis->fresh(),
                'trade_signal' => $tradeSignal,
            ]);
        });
    }

    private function buildContext(
        TechnicalContextService $service,
        string $symbol,
        string $executionTimeframe
    ): array {
        foreach (['build', 'generate', 'getContext', 'analyze'] as $method) {
            if (method_exists($service, $method)) {
                $result = $service->{$method}($symbol, $executionTimeframe);

                if (is_array($result)) {
                    return $result;
                }

                if (method_exists($result, 'toArray')) {
                    return $result->toArray();
                }
            }
        }

        throw new \RuntimeException(
            'TechnicalContextService tidak punya method build/generate/getContext/analyze. Sesuaikan nama method di controller.'
        );
    }

    private function contextValue(array $context, array $paths, mixed $default = null): mixed
    {
        foreach ($paths as $path) {
            $value = data_get($context, $path);

            if ($value !== null) {
                return $value;
            }
        }

        return $default;
    }

    private function appendNote(?string $oldNote, ?string $newNote): string
    {
        $newNote = trim((string) $newNote);

        if ($newNote === '') {
            return (string) $oldNote;
        }

        $timestamp = now()->format('Y-m-d H:i:s');

        return trim(($oldNote ? $oldNote . PHP_EOL : '') . '[' . $timestamp . '] ' . $newNote);
    }
}